spring:
  profiles:
    active: dev
  data:
    mongodb:
      host: ec2-13-59-252-195.us-east-2.compute.amazonaws.com
      port: 27017
      database: logStore
  servlet:
    multipart:
      enabled: true
#      file-size: 2KB
      max-file-size: 2MB
#      max-request-size: 3MB

app:
  upload:
    batchSize: 200
    threadPoolSize: 10

server:
  port: 8090

